ratrace/common/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .views import (
    ClockInOutView,
    ProfileView,
    CompanyAddView,
    CompanyListView,
    DepartmentListView,
    DepartmentAddView,
)


app_name = "common"

urlpatterns = [
    path("", TemplateView.as_view(template_name="common/index.html"), name="index"),
    path(
        "settings/",
        TemplateView.as_view(template_name="common/settings.html"),
        name="settings",
    ),
    path("clock-in-out", ClockInOutView.as_view(), name="clockinout"),
    path("user/login", LoginView.as_view(), name="login"),
    path("user/profile/<user_id>", ProfileView.as_view(), name="profile"),
    # companies
    # TODO: company-add in companies
    path("companies/", CompanyListView.as_view(), name="company-list"),
    path(
        "companies/<int:pk>/", views.CompanyDetailView.as_view(), name="company-detail"
    ),
    path("companies/add", CompanyAddView.as_view(), name="company-add"),
    path(
        "companies/<int:pk>/update/",
        views.CompanyUpdateView.as_view(),
        name="company-update",
    ),
    path(
        "companies/<int:pk>/delete/",
        views.CompanyDeleteView.as_view(),
        name="company-delete",
    ),
    path(
        "companies/<int:pk>/select",
        views.CompanySelectListView.as_view(),
        name="company-select",
    ),
    # Departments
    path("departments/", DepartmentListView.as_view(), name="departments-list"),
    path(
        "departments/<int:pk>/",
        views.DepartmentDetailView.as_view(),
        name="departments-detail",
    ),
    path("departments/add", DepartmentAddView.as_view(), name="departments-add"),
    path(
        "departments/<int:pk>/update/",
        views.DepartmentUpdateView.as_view(),
        name="departments-update",
    ),
    path(
        "departments/<int:pk>/delete/",
        views.DepartmentDeleteView.as_view(),
        name="departments-delete",
    ),
    # FunctionGroups
    path(
        "functiongroups/",
        views.FunctionGroupListView.as_view(),
        name="functiongroups-list",
    ),
    path(
        "functiongroups/<int:pk>/",
        views.FunctionGroupDetailView.as_view(),
        name="functiongroups-detail",
    ),
    path(
        "functiongroups/add",
        views.FunctionGroupAddView.as_view(),
        name="functiongroups-add",
    ),
    path(
        "functiongroups/<int:pk>/update/",
        views.FunctionGroupUpdateView.as_view(),
        name="functiongroups-update",
    ),
    path(
        "functiongroups/<int:pk>/delete/",
        views.FunctionGroupDeleteView.as_view(),
        name="functiongroups-delete",
    ),
    # Functions
    path(
        "functions/",
        views.FunctionListView.as_view(),
        name="functions-list",
    ),
    path(
        "functions/<int:pk>/",
        views.FunctionDetailView.as_view(),
        name="functions-detail",
    ),
    path(
        "functions/add",
        views.FunctionAddView.as_view(),
        name="functions-add",
    ),
    path(
        "functions/<int:pk>/update/",
        views.FunctionUpdateView.as_view(),
        name="functions-update",
    ),
    path(
        "functions/<int:pk>/delete/",
        views.FunctionDeleteView.as_view(),
        name="functions-delete",
    ),
    # Positions
    path(
        "positions/",
        views.PositionListView.as_view(),
        name="positions-list",
    ),
    path(
        "positions/<int:pk>/",
        views.PositionDetailView.as_view(),
        name="positions-detail",
    ),
    path(
        "positions/add",
        views.PositionAddView.as_view(),
        name="positions-add",
    ),
    path(
        "positions/<int:pk>/update/",
        views.PositionUpdateView.as_view(),
        name="positions-update",
    ),
    path(
        "positions/<int:pk>/delete/",
        views.PositionDeleteView.as_view(),
        name="positions-delete",
    ),
# EmployeeTypes
    path(
        "employeetypes/",
        views.EmployeeTypeListView.as_view(),
        name="employeetypes-list",
    ),
    path(
        "employeetypes/<int:pk>/",
        views.EmployeeTypeDetailView.as_view(),
        name="employeetypes-detail",
    ),
    path(
        "employeetypes/add",
        views.EmployeeTypeAddView.as_view(),
        name="employeetypes-add",
    ),
    path(
        "employeetypes/<int:pk>/update/",
        views.EmployeeTypeUpdateView.as_view(),
        name="employeetypes-update",
    ),
    path(
        "employeetypes/<int:pk>/delete/",
        views.EmployeeTypeDeleteView.as_view(),
        name="employeetypes-delete",
    ),
# Employees
    path(
        "employees/",
        views.EmployeeListView.as_view(),
        name="employees-list",
    ),
    path(
        "employees/<int:pk>/",
        views.EmployeeDetailView.as_view(),
        name="employees-detail",
    ),
    path(
        "employees/add",
        views.EmployeeAddView.as_view(),
        name="employees-add",
    ),
    path(
        "employees/<int:pk>/update/",
        views.EmployeeUpdateView.as_view(),
        name="employees-update",
    ),
    path(
        "employees/<int:pk>/delete/",
        views.EmployeeDeleteView.as_view(),
        name="employees-delete",
    ),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ratrace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("ratrace.common.urls")),
    path("schedule", include("ratrace.schedule.urls")),
    path("accounting", include("ratrace.accounting.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ratrace/common/models.py
from decimal import Decimal

import enumfields
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.core.validators import (
    MinValueValidator,
    MaxValueValidator,
)
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django_countries.fields import CountryField
from enumfields import Enum, EnumField

User = get_user_model()


# borrowed from MedUX
class CreatedModifiedModel(models.Model):
    """A simple mixin for model classes that need to have created/modified fields."""

    created = models.DateTimeField(editable=False, default=timezone.now)
    modified = models.DateTimeField(editable=False, auto_now=True)

    class Meta:
        abstract = True


class Company(CreatedModifiedModel):
    name = models.CharField(max_length=255)
    logo = models.ImageField(upload_to="companylogos/", blank=True, null=True)
    address = models.CharField(_("Street"), max_length=256)
    city = models.CharField(_("City"), max_length=64)
    country = CountryField(_("Country"), default="Austria")
    zip_code = models.CharField(_("ZIP"), max_length=7)
    contact_tel = models.CharField(_("Phone"), max_length=15)
    contact_fax = models.CharField(_("Fax"), max_length=20, blank=True)
    contact_email = models.EmailField(_("E-Mail"))
    website = models.URLField(_("Website"), max_length=200, blank=True)

    # departments
    # employees
    # coreworkingtime = models.ForeignKey(CoreWorkingTimeBlock, on_delete=models.PROTECT)

    def __str__(self):
        return self.name


class Department(CreatedModifiedModel):
    """TODO: Maybe find a better name. departments are not a good name for GPs, etc."""

    name = models.CharField(max_length=255)
    active = models.BooleanField(default=True)
    company = models.ForeignKey(
        Company, on_delete=models.CASCADE, null=True, related_name="department"
    )

    def __str__(self):
        return self.name


class FunctionGroup(CreatedModifiedModel):
    """Used for grouping/ordering of Functions/Slots across departments

    e.g.
    * Endoscopy: Endoscopy I, Endoscopy II, Bronchoscopy have the function group "Endoscopy"
    """

    name = models.CharField(max_length=255)
    short_name = models.CharField(max_length=15, blank=True, unique=True)

    def __str__(self):
        return self.name


class Position(CreatedModifiedModel):
    # TODO: we could delete this - this is what Department is for
    """A position in a department where some work is to be done.

    A Position must be occupied for a certain amount of hours per week, e.g. Mo-Fr 9:00-15:00
    """

    name = models.CharField(max_length=255)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name="position_department")

    def __str__(self):
        return self.name


class Function(CreatedModifiedModel):
    """A role/function that any employee may take in a department, according to his/her status/training.

    This could be:
    * Laboratory, Endoscopy, ambulance etc.
    * Reception, Assistant, OP, etc.

    This is needed, as e.g. only nurses with "surgery" training can take slots in the surgery schedule.
    """

    name = models.CharField(max_length=255)
    short_name = models.CharField(max_length=15, blank=True, unique=True)
    group = models.ForeignKey(FunctionGroup, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class EmployeeType(CreatedModifiedModel):
    """Type of employment

    e.g. MTA, etc."""

    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Employee(CreatedModifiedModel):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    functions = models.ManyToManyField(
        Function, blank=True, related_name="employee_function"
    )
    type = models.ForeignKey(
        EmployeeType, on_delete=models.PROTECT, null=True, blank=True
    , related_name="employee_type")
    company = models.ForeignKey(
        Company, on_delete=models.CASCADE, null=True, related_name="employee_company"
    )
    department = models.ManyToManyField(Department, related_name="employee_department")
    position = models.ManyToManyField(Position, related_name="employee_position")
    # FIXME: this can be changed over time too. Should be in the contract/CoreWorkingTime
    holiday_entitlement_hours = models.PositiveSmallIntegerField(
        help_text=_("Hours of holidays per year."), default=0
    )

    def __str__(self):
        return str(self.user)

    def vacations_consumed(self) -> int:
        # TODO: calculate correctly: only this year
        sum = 0
        for vacation in self.vacations.values():  # type: Vacation
            sum += len(vacation)
        return sum

    def vacation_balance(self) -> int:
        """:return: hours of current vacation balance"""

        return self.vacation_balances.order_by("date").last().balance


# FIXME: This part caused a Related name error "User has no Employee" - Accoding to this https://stackoverflow.com/questions/63211265/relatedobjectdoesnotexist-user-has-no-profile the super.save() method is missing

# @receiver(post_save, sender=User)
# def create_employee(sender, instance: User, created, **kwargs):
#     """Create Employee for every new User."""
#
#     if created:
#         Employee.objects.create(user=instance)
#     instance.employee.save()


class VacationType(models.Model):
    """Type of vacations: normal, special leave, etc."""

    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    weight = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return self.name


class Vacation(CreatedModifiedModel):
    """A vacation entry of one employee"""

    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name="vacations"
    )
    type = models.ForeignKey(VacationType, default=1, on_delete=models.SET_DEFAULT)
    start = models.DateField()
    end = models.DateField()

    @property
    def days(self) -> int:
        """The length of the vacation in days"""
        return (self.end - self.start).days

    def __len__(self):
        return self.days * 24

    def clean(self):
        if self.start >= self.end:
            raise ValidationError(_("'start' can not occur timely after 'end'."))


class VacationBalance(CreatedModifiedModel):
    """Current "balance" of vacation of an employee

    This should not be necessary to add manually, as it is calculated and saved
    automatically when consuming vacation
    However, At the beginning of employing someone, it may be helpful to create the "offset" of his balance.
    """

    employee = models.ForeignKey(
        Employee, on_delete=models.CASCADE, related_name="vacation_balances"
    )
    date = models.DateField()
    balance = models.PositiveIntegerField(default=0)

    # TODO: creating balances must be done automatically by a "cron"job:
    #  when currently "on vacations" today, reduce employee's vacation_balance by 24h (8 hours?)

    # TODO: make sure that any employee gets a VacationBalance at creation, OK if 0


class CoreWorkingTimeBlock(models.Model):
    """A block at one week day with working times.

    This is needed as basic data for an employment.
    Many of these blocks form a CoreWorkingTime.
    """

    class DaysOfWeek(Enum):
        MON = 1
        TUE = 2
        WED = 3
        THU = 4
        FRI = 5
        SAT = 6
        SUN = 7

        class Labels:
            MON = _("Monday")
            TUE = _("Tuesday")
            WED = _("Wednesday")
            THU = _("Thursday")
            FRI = _("Friday")
            SAT = _("Saturday")
            SUN = _("Sunday")

    day_of_week = EnumField(DaysOfWeek)
    start = models.TimeField()
    end = models.TimeField()
    core_working_time = models.ForeignKey(
        "CoreWorkingTime", on_delete=models.CASCADE, related_name="blocks"
    )
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, null=True)

    def __str__(self):
        # TODO: output something more meaningful
        user = self.core_working_time.employee.user  # type: User

        # noinspection PyUnresolvedReferences
        return (
            f"{user.first_name} {user.last_name}: "
            f"{self.day_of_week.label}: {self.start.hour:02d}:{self.start.minute:02d} - "
            f"{self.end.hour:02d}:{self.end.minute:02d}"
        )

    @property
    def employee(self):
        return self.core_working_time.employee


class CoreWorkingTime(CreatedModifiedModel):
    """represents a contract for working hours with an employee

    This could change over time, so it is possible to create new CoreWorkingTimes
    with a different start_date.
    """

    weekly_working_hours = models.DecimalField(
        default=settings.FULL_EMPLOYMENT_HOURS, decimal_places=2, max_digits=5
    )
    employment_percentage = models.DecimalField(
        default=1.0,
        max_digits=3,
        decimal_places=2,
        validators=[MinValueValidator(0.0), MaxValueValidator(1.0)],
    )
    # FIXME: These are no corworkingtimes but only dates (like date of employment
    valid_start = models.DateField()
    valid_end = models.DateField(blank=True, null=True)

    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)

    def __str__(self):
        return str([str(block) for block in self.blocks.order_by("day_of_week")])

    @property
    def days_per_week(self):
        return self.blocks.values_list("day_of_week").distinct().count()
        # return self.blocks.distinct("day_of_week").count()

ratrace/common/views/department.py
from django.urls import reverse
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    DeleteView,
    UpdateView,
)
from django.utils.translation import gettext_lazy as _
from ratrace.common.models import Department


class DepartmentListView(ListView):
    model = Department
    fields = "__all__"
    template_name = "common/department_list.html"
    queryset = Department.objects.all()
    context_object_name = "departments"


class DepartmentDetailView(DetailView):
    model = Department


class DepartmentAddView(CreateView):
    template_name = "common/department_form.html"
    model = Department
    fields = "__all__"
    success_url = "/departments"
    extra_context = {"title": _("Add department")}

    # def get_success_url(self):
    #     if self.request.POST.get("save"):
    #         return reverse("/departments")
    #     elif self.request.POST.get("save_and_addnew"):
    #         return reverse("/departments/add", kwargs={"pk": self.object.pk})


class DepartmentUpdateView(UpdateView):
    model: Department
    fields = "__all__"
    template_name = "common/department_form.html"
    queryset = Department.objects.all()
    success_url = "/departments"
    extra_context = {"title": _("Edit department")}


class DepartmentDeleteView(DeleteView):
    model = Department
    template_name = "common/confirm_delete.html"
    success_url = "/departments"

ratrace/common/templates/common/department_list.html
{% extends 'layouts/base.html' %}
{% load static i18n %}


{% block title %}{% trans 'Department list' %}{% endblock %}

{% block content %}
    <div class="p-md-4 p-sm-3 rounded-sm page-header">
        <span class="header-text">{% trans 'Departments' %}</span>
    </div>
    <div class="container-fluid">

<div class="row">
    <div class="col">
        <a href="{% url 'common:departments-add' %}"
                   class="btn btn-new">{% trans 'New department' %}</a>
    </div>
</div>

        <div class="row">
        <div class="col">
          <table class="rr-table table table-striped ">
{#            {% if departments %}#}
<th class="table-heading">{% trans 'Active' %}</th>
              <th class="table-heading">{% trans 'Department...' %}</th>
          <th class="table-heading">{% trans '...within company' %}</th>
          <th class="table-heading"></th>
            {% for department in object_list %}
                <tr>
                <td class="table-cell-center">
                    {% if department.active %}
                      <i class="bi bi-check2-circle"></i>
                    {% else %}
                      <i class="bi bi-x-circle"></i>
                    {% endif %}
                  </td>
                <td>
                    <a href="{% url 'common:departments-detail' department.pk%}" class="list-name">{{ department.name }}</a>
                </td>
                <td>
                    <a href="{% url 'common:company-detail' department.company.pk%}" class="list-name">{{ department.company.name }}</a>
                </td>
                <td>
                    <a href="{% url 'common:departments-update' department.pk%}" class="btn btn-sm btn-edit"><i class="bi bi-pencil-square"></i></a>
                        <a href="{% url 'common:departments-delete' department.pk%}" class="btn btn-sm btn-delete"><i class="bi bi-x-square"></i></a>
                </td>
                </tr>
            {% endfor %}

{#            {% else %}#}
{#                <div class="display-7">{% trans 'Currently there are no departments stored in the database' %}</div>#}
{#            {% endif %}#}
          </table>
        </div>
        </div>

            <div class="list-footer">

            </div>

    </div>
{% endblock %}

ratrace/common/templates/common/employeetype_detail.html
{% extends 'layouts/base.html' %}
{% load static i18n %}

{% block title %}{% trans 'Employee-Type: ' %}{{ object.name }}{% endblock %}

{% block content %}
  <div class="row p-md-4 p-sm-3 rounded-sm page-header">
    <div class="col header-text">
      {{ object.name }}
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="btn-group" role="group" aria-label="Department details">
        <a class="btn btn-cancel"
           href="{% url 'common:employeetypes-list' %}"
           class="btn btn-cancel">{% trans 'Back' %}</a>

      </div>
      <div class="btn-group" role="group" aria-label="Department details actions">
        <a class="btn btn-edit"
           href="{% url 'common:employeetypes-update' object.pk %}"
           class="btn btn-edit">{% trans 'Edit' %}</a>
        <a class="btn btn-delete"
           href="{% url 'common:employeetypes-delete' object.pk %}"
           class="btn btn-delete">{% trans 'Delete' %}</a>
      </div>

    </div>

    <div class="container-fluid">


    <div class="row">
      <div class="col-5 section-header">{% translate 'Assigned Employees' %}</div>
      <div class="col-4"></div>
      <div class="col-3 div-btn-new">
        <a href="{# TODO: add employees URLs... {% url 'common:employees-add' %}#}"
           class="btn btn-new">{% translate 'New employee' %}</a>
      </div>
    </div>
    <div class="col">
      <table class="rr-table table table-striped ">
        {% if object.employee_type.all %}
          <th class="table-heading">{% trans 'Employee' %}</th>
          <th class="table-heading">{% trans 'Functions' %}</th>


          {% for employee in object.employee_type.all %}
            <tr>
              <td>
                  <a href="">{{ employee.user }}</a>
              </td>
              <td>
                {% if employee.functions %}
                  {% for function in employee.functions.all %}
                      <a href="{% url 'common:functions-detail' function.pk %}">{{ function.name }}</a> <br>
                  {% endfor %}
                {% else %}
                <i class="bi bi-dash-circle-dotted"></i>
              {% endif %}
              </td>

            </tr>


          {% endfor %}
        {% else %}
          {% trans 'There are currently no employees assigned to ' %} {{ object.name }}
        {% endif %}
      </table>
    </div>






{% endblock %}

ratrace/common/templates/common/employeetype_list.html
{% extends 'layouts/base.html' %}
{% load static i18n %}


{% block title %}{% trans 'Employee Type' %}{% endblock %}

{% block content %}
    <div class="p-md-4 p-sm-3 rounded-sm page-header">
        <span class="header-text">{% trans 'Employee-Types' %}</span>
    </div>
    <div class="container-fluid">

<div class="row">
    <div class="col">
        <a href="{% url 'common:employeetypes-add' %}"
                   class="btn btn-new">{% trans 'New type' %}</a>
    </div>
</div>

        <div class="row">
        <div class="col">
            <ul>
                {% for type in object_list %}
                <li>
                    <a href="{% url 'common:employeetypes-detail' type.pk %}" class="list-name">{{ type.name }}</a>
                </li>
                {% endfor %}
            </ul>



{% comment %}          <table class="rr-table table table-striped ">
{#            {% if object_list %}#}

          <th class="table-heading">{% trans 'Type' %}</th>
          <th class="table-heading">{% trans 'Assigned emloyees' %}</th>
          <th></th>
            {% for type in object_list %}
                <tr>
                <td class="table-cell-center">
                    {% if function.active %}
                      <i class="bi bi-check2-circle"></i>
                    {% else %}
                      <i class="bi bi-x-circle"></i>
                    {% endif %}
                  </td>
                <td>
                    <a href="{% url 'common:functions-detail' function.pk %}" class="list-name">{{ function.name }}</a>
                </td>
                <td>
                    <span class="list-name">{{ function.short_name }}</span>
                </td>
                <td>
                    <a href="{% url 'common:functiongroups-detail' function.group.pk %}" class="list-name">{{ function.group }}</a>
                </td>
                <td>
                    <a href="{% url 'common:departments-detail' function.department.pk %}" class="list-name">{{ function.department }}</a>
                </td>
                <td>
                    <a href="{% url 'common:functions-update' function.pk%}" class="btn btn-sm btn-edit"><i class="bi bi-pencil-square"></i></a>
                        <a href="{% url 'common:functions-delete' function.pk%}" class="btn btn-sm btn-delete"><i class="bi bi-x-square"></i></a>
                </td>
                </tr>
            {% endfor %}

{#            {% else %}#}
{#                <div class="display-7">{% trans 'Currently there are no functiongroups stored in the database' %}</div>#}
{#            {% endif %}#}
          </table>{% endcomment %}
        </div>
        </div>

            <div class="list-footer">

            </div>

    </div>
{% endblock %}

ratrace/common/templates/common/index.html
{% extends 'layouts/base.html' %}

{% block title %}Ratrace{% endblock %}

{% block content %}
    <div class="p-md-4 p-sm-3 rounded-sm">
        <h2 class="display-4">Index</h2>
    </div>




{% endblock %}

ratrace/common/templates/common/settings.html
{% extends 'layouts/base.html' %}
{% load static i18n %}


{% block title %}{% trans 'Settings' %}{% endblock %}

{% block content %}
    <div class="p-md-4 p-sm-3 rounded-sm page-header">
        <span class="header-text">{% trans 'Settings' %}
    </div>
    <div class="container-fluid">


        <div class="row">
            <div class="row section-header">
                {% trans 'Company' %}
            </div>
            <div class="row  list-item">

                <div class="row">
                    <div class="col-10">
                        <span class="list-name"><a href="{% url 'common:company-list' %}">Companies</a></span>
                    </div>

                    <div class="col-2">
                        <button class="btn btn-sm btn-new"><a href="{% url 'common:company-add' %}"><i class="bi bi-plus-circle"></i></a></button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-10">
                        <span class="list-name"><a href="{% url 'common:departments-list' %}">Departments</a></span>
                    </div>
                    <div class="col-2">
                        <button class="btn btn-sm btn-new"><a href="{% url 'common:departments-add' %}"><i class="bi bi-plus-circle"></i></a></button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-10">
                        <span class="list-name"><a href="{% url 'common:positions-list' %}">Positions</a></span>
                    </div>

                    <div class="col-2">
                        <button class="btn btn-sm btn-new"><a href="{% url 'common:positions-add' %}"><i class="bi bi-plus-circle"></i></a></button>
                    </div>
                </div>

        </div>
            </div>


        <div class="row">
            <div class="row section-header">
                {% trans 'Function' %}
            </div>
            <div class="row  list-item">

                <div class="row">
                    <div class="col-10">
                        <span class="list-name"><a href="{% url 'common:functiongroups-list' %}">Function-Groups</a></span>
                    </div>

                    <div class="col-2">
                        <button class="btn btn-sm btn-new"><a href="{% url 'common:functiongroups-add' %}"><i class="bi bi-plus-circle"></i></a></button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-10">
                        <span class="list-name"><a href="{% url 'common:functions-list' %}">Functions</a></span>
                    </div>
                    <div class="col-2">
                        <button class="btn btn-sm btn-new"><a href="{% url 'common:functions-add' %}"><i class="bi bi-plus-circle"></i></a></button>
                    </div>
                </div>

        </div>
            </div>



        <div class="row">
            <div class="row section-header">
                {% trans 'Employee' %}
            </div>
            <div class="row  list-item">
                <div class="row">
                    <div class="col-10">
                        <span class="list-name"><a href="{% url 'common:employeetypes-list' %}">Employee-Types</a></span>
                    </div>

                    <div class="col-2">
                        <button class="btn btn-sm btn-new"><a href="{% url 'common:employeetypes-add' %}"><i class="bi bi-plus-circle"></i></a></button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-10">
                        <span class="list-name"><a href="{% url 'common:employees-list' %}">Employees</a></span>
                    </div>

                    <div class="col-2">
                        <button class="btn btn-sm btn-new"><a href="{% url 'common:employees-add' %}"><i class="bi bi-plus-circle"></i></a></button>
                    </div>
                </div>
            </div>
            </div>



        <div class="row">
            <div class="row section-header">
                {% trans 'Core Working Time' %}
            </div>
            <div class="row  list-item">
                <div class="row">
                    <div class="col-10">
                        <span class="list-name"><a href="">Core Working Times</a></span>
                    </div>

                    <div class="col-2">
                        <button class="btn btn-sm btn-new"><a href=""><i class="bi bi-plus-circle"></i></a></button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-10">
                        <span class="list-name"><a href="">Core Working Time Blocks</a></span>
                    </div>

                    <div class="col-2">
                        <button class="btn btn-sm btn-new"><a href=""><i class="bi bi-plus-circle"></i></a></button>
                    </div>
                </div>
            </div>
            </div>



        <div class="row">
            <div class="row section-header">
                {% trans 'Vacation' %}
            </div>
            <div class="row  list-item">
                <div class="row">
                    <div class="col-10">
                        <span class="list-name"><a href="">Vacation Types</a></span>
                    </div>

                    <div class="col-2">
                        <button class="btn btn-sm btn-new"><a href=""><i class="bi bi-plus-circle"></i></a></button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-10">
                        <span class="list-name"><a href="">Vacation balances</a></span>
                    </div>

                    <div class="col-2">
                        <button class="btn btn-sm btn-new"><a href=""><i class="bi bi-plus-circle"></i></a></button>
                    </div>
                </div>
                <div class="row">
                    <div class="col-10">
                        <span class="list-name"><a href="">Vacations</a></span>
                    </div>

                    <div class="col-2">
                        <button class="btn btn-sm btn-new"><a href=""><i class="bi bi-plus-circle"></i></a></button>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>





{% endblock %}