ratrace/common/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .views import (
    ClockInOutView,
    ProfileView,
    CompanyAddView,
    CompanyListView,
    DepartmentListView,
    DepartmentAddView,
)


app_name = "common"

urlpatterns = [
    path("", TemplateView.as_view(template_name="common/index.html"), name="index"),
    path(
        "settings/",
        TemplateView.as_view(template_name="common/settings.html"),
        name="settings",
    ),
    path("clock-in-out", ClockInOutView.as_view(), name="clockinout"),
    path("user/login", LoginView.as_view(), name="login"),
    path("user/profile/<user_id>", ProfileView.as_view(), name="profile"),
    # companies
    # TODO: company-add in companies
    path("companies/", CompanyListView.as_view(), name="company-list"),
    path(
        "companies/<int:pk>/", views.CompanyDetailView.as_view(), name="company-detail"
    ),
    path("companies/add", CompanyAddView.as_view(), name="company-add"),
    path(
        "companies/<int:pk>/update/",
        views.CompanyUpdateView.as_view(),
        name="company-update",
    ),
    path(
        "companies/<int:pk>/delete/",
        views.CompanyDeleteView.as_view(),
        name="company-delete",
    ),
    path(
        "companies/<int:pk>/select",
        views.CompanySelectListView.as_view(),
        name="company-select",
    ),
    # Departments
    path("departments/", DepartmentListView.as_view(), name="departments-list"),
    path(
        "departments/<int:pk>/",
        views.DepartmentDetailView.as_view(),
        name="departments-detail",
    ),
    path("departments/add", DepartmentAddView.as_view(), name="departments-add"),
    path(
        "departments/<int:pk>/update/",
        views.DepartmentUpdateView.as_view(),
        name="departments-update",
    ),
    path(
        "departments/<int:pk>/delete/",
        views.DepartmentDeleteView.as_view(),
        name="departments-delete",
    ),
    # FunctionGroups
    path(
        "functiongroups/",
        views.FunctionGroupListView.as_view(),
        name="functiongroups-list",
    ),
    path(
        "functiongroups/<int:pk>/",
        views.FunctionGroupDetailView.as_view(),
        name="functiongroups-detail",
    ),
    path(
        "functiongroups/add",
        views.FunctionGroupAddView.as_view(),
        name="functiongroups-add",
    ),
    path(
        "functiongroups/<int:pk>/update/",
        views.FunctionGroupUpdateView.as_view(),
        name="functiongroups-update",
    ),
    path(
        "functiongroups/<int:pk>/delete/",
        views.FunctionGroupDeleteView.as_view(),
        name="functiongroups-delete",
    ),
    # Functions
    path(
        "functions/",
        views.FunctionListView.as_view(),
        name="functions-list",
    ),
    path(
        "functions/<int:pk>/",
        views.FunctionDetailView.as_view(),
        name="functions-detail",
    ),
    path(
        "functions/add",
        views.FunctionAddView.as_view(),
        name="functions-add",
    ),
    path(
        "functions/<int:pk>/update/",
        views.FunctionUpdateView.as_view(),
        name="functions-update",
    ),
    path(
        "functions/<int:pk>/delete/",
        views.FunctionDeleteView.as_view(),
        name="functions-delete",
    ),
    # Positions
    path(
        "positions/",
        views.PositionListView.as_view(),
        name="positions-list",
    ),
    path(
        "positions/<int:pk>/",
        views.PositionDetailView.as_view(),
        name="positions-detail",
    ),
    path(
        "positions/add",
        views.PositionAddView.as_view(),
        name="positions-add",
    ),
    path(
        "positions/<int:pk>/update/",
        views.PositionUpdateView.as_view(),
        name="positions-update",
    ),
    path(
        "positions/<int:pk>/delete/",
        views.PositionDeleteView.as_view(),
        name="positions-delete",
    ),
# EmployeeTypes
    path(
        "employeetypes/",
        views.EmployeeTypeListView.as_view(),
        name="employeetypes-list",
    ),
    path(
        "employeetypes/<int:pk>/",
        views.EmployeeTypeDetailView.as_view(),
        name="employeetypes-detail",
    ),
    path(
        "employeetypes/add",
        views.EmployeeTypeAddView.as_view(),
        name="employeetypes-add",
    ),
    path(
        "employeetypes/<int:pk>/update/",
        views.EmployeeTypeUpdateView.as_view(),
        name="employeetypes-update",
    ),
    path(
        "employeetypes/<int:pk>/delete/",
        views.EmployeeTypeDeleteView.as_view(),
        name="employeetypes-delete",
    ),
# Employees
    path(
        "employees/",
        views.EmployeeListView.as_view(),
        name="employees-list",
    ),
    path(
        "employees/<int:pk>/",
        views.EmployeeDetailView.as_view(),
        name="employees-detail",
    ),
    path(
        "employees/add",
        views.EmployeeAddView.as_view(),
        name="employees-add",
    ),
    path(
        "employees/<int:pk>/update/",
        views.EmployeeUpdateView.as_view(),
        name="employees-update",
    ),
    path(
        "employees/<int:pk>/delete/",
        views.EmployeeDeleteView.as_view(),
        name="employees-delete",
    ),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ratrace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("ratrace.common.urls")),
    path("schedule", include("ratrace.schedule.urls")),
    path("accounting", include("ratrace.accounting.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ratrace/common/forms.py
from crispy_forms.bootstrap import (
    PrependedAppendedText,
)
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout
from django import forms

from .models import ClockingTimeStamp, Company, Position, Employee


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = "__all__"
        widgets = {}


class ClockInOutForm(forms.ModelForm):
    class Meta:
        model = ClockingTimeStamp
        exclude = ("recorded_by",)

    password = forms.CharField(widget=forms.PasswordInput)

    helper = FormHelper()
    helper.form_class = "form-horizontal"
    helper.layout = Layout(
        "employee",
        "password",
        "logging",  # TODO: use RadioButtonGroup
        PrependedAppendedText(  # TODO: create own widget, fix datepicker
            "timestamp",
            "-15min",
            # TODO make buttons here. not possible with PrependedAppendedText, as only safe HTML is allowed.
            "+15min",
        ),
        "comment",
    )

ratrace/common/views/company.py
from django.contrib.auth.views import LoginView as DjangoLoginView
from django.http import HttpRequest
from django.shortcuts import render
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    DeleteView,
)

from ..forms import ClockInOutForm, CompanyForm
from ..models import ClockingTimeStamp, Company


class ClockInOutView(CreateView):
    model = ClockingTimeStamp
    form_class = ClockInOutForm

    def post(self, request, *args, **kwargs):
        # request.
        super().post(request, *args, **kwargs)


class LoginView(DjangoLoginView):
    success_url = "/user/profile"


class ProfileView(DetailView):
    pass


class CompanyAddView(CreateView):
    model = Company
    form_class = CompanyForm
    success_url = "/companies"
    extra_context = {"title": _("Add company")}


class CompanyDetailView(DetailView):
    model = Company


class CompanyListView(ListView):
    model = Company
    template_name = "common/company_list.html"
    context_object_name = "companies"


class CompanyUpdateView(UpdateView):
    model: Company
    template_name = "common/company_form.html"
    form_class = CompanyForm
    queryset = Company.objects.all()
    success_url = "/companies"
    extra_context = {"title": _("Edit company")}


class CompanyDeleteView(DeleteView):
    model = Company
    template_name = "common/confirm_delete.html"
    success_url = "/companies"


class CompanySelectListView(ListView):
    model = Company
    template_name = "common/company_list_table.html"

    def post(self, request: HttpRequest, pk):
        request.session["current_company_id"] = pk
        return render(request, self.template_name)

    # def get(self, request: HttpRequest, *args, **kwargs):
    #     request.session["current_company_id"] = request.GET["company_id"]
    #     super().get(args, kwargs)
    #     return redirect(reverse("common:company-list"))

ratrace/common/views/department.py
from django.urls import reverse
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    DeleteView,
    UpdateView,
)
from django.utils.translation import gettext_lazy as _
from ratrace.common.models import Department


class DepartmentListView(ListView):
    model = Department
    fields = "__all__"
    template_name = "common/department_list.html"
    queryset = Department.objects.all()
    context_object_name = "departments"


class DepartmentDetailView(DetailView):
    model = Department


class DepartmentAddView(CreateView):
    template_name = "common/department_form.html"
    model = Department
    fields = "__all__"
    success_url = "/departments"
    extra_context = {"title": _("Add department")}

    # def get_success_url(self):
    #     if self.request.POST.get("save"):
    #         return reverse("/departments")
    #     elif self.request.POST.get("save_and_addnew"):
    #         return reverse("/departments/add", kwargs={"pk": self.object.pk})


class DepartmentUpdateView(UpdateView):
    model: Department
    fields = "__all__"
    template_name = "common/department_form.html"
    queryset = Department.objects.all()
    success_url = "/departments"
    extra_context = {"title": _("Edit department")}


class DepartmentDeleteView(DeleteView):
    model = Department
    template_name = "common/confirm_delete.html"
    success_url = "/departments"

ratrace/common/views/employee.py
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    DeleteView,
    UpdateView,
)
from django.utils.translation import gettext_lazy as _
from ratrace.common.models import Employee


class EmployeeListView(ListView):
    model = Employee
    fields = "__all__"
    template_name = "common/employee_list.html"
    queryset = Employee.objects.all()
    context_object_name = "employees"


class EmployeeDetailView(DetailView):
    model = Employee


class EmployeeAddView(CreateView):
    template_name = "common/employee_form.html"
    model = Employee
    fields = "__all__"
    success_url = "/employees"
    extra_context = {"title": _("Add Employee")}


class EmployeeUpdateView(UpdateView):
    model: Employee
    fields = "__all__"
    template_name = "common/employee_form.html"
    queryset = Employee.objects.all()
    success_url = "/employees"
    extra_context = {"title": _("Edit Employee")}


class EmployeeDeleteView(DeleteView):
    model = Employee
    template_name = "common/confirm_delete.html"
    success_url = "/employees"

ratrace/common/views/employeetype.py
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    DeleteView,
    UpdateView,
)
from django.utils.translation import gettext_lazy as _
from ratrace.common.models import EmployeeType, Employee


class EmployeeTypeListView(ListView):
    model = EmployeeType
    fields = "__all__"
    template_name = "common/employeetype_list.html"
    queryset = EmployeeType.objects.all()
    context_object_name = "employeetypes"


class EmployeeTypeDetailView(DetailView):
    model = EmployeeType


class EmployeeTypeAddView(CreateView):
    template_name = "common/employeetype_form.html"
    model = EmployeeType
    fields = "__all__"
    success_url = "/employeetypes"
    extra_context = {"title": _("Add Employeetype")}

    # TODO: forms.MultipleChoiceField(widget=ChEckbox)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["employee_list"] = Employee.objects.all()
        return context

class EmployeeTypeUpdateView(UpdateView):
    model: EmployeeType
    fields = "__all__"
    template_name = "common/employeetype_form.html"
    queryset = EmployeeType.objects.all()
    success_url = "/employeetypes"
    extra_context = {"title": _("Edit Employeetype")}


class EmployeeTypeDeleteView(DeleteView):
    model = EmployeeType
    template_name = "common/confirm_delete.html"
    success_url = "/employeetypes"

ratrace/common/views/function.py
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    DeleteView,
    UpdateView,
)
from django.utils.translation import gettext_lazy as _
from ratrace.common.models import Function


class FunctionListView(ListView):
    model = Function
    fields = "__all__"
    template_name = "common/function_list.html"
    queryset = Function.objects.all()
    context_object_name = "functions"


class FunctionDetailView(DetailView):
    model = Function


# FIXME: Save and successurl not working on save or update


class FunctionAddView(CreateView):
    template_name = "common/function_form.html"
    model = Function
    fields = "__all__"
    success_url = "/functions"
    extra_context = {"title": _("Add function")}


class FunctionUpdateView(UpdateView):
    model: Function
    fields = "__all__"
    template_name = "common/function_form.html"
    queryset = Function.objects.all()
    success_url = "/functions"
    extra_context = {"title": _("Edit function")}


class FunctionDeleteView(DeleteView):
    model = Function
    template_name = "common/confirm_delete.html"
    success_url = "/functions"

ratrace/common/views/functiongroup.py
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    DeleteView,
    UpdateView,
)
from django.utils.translation import gettext_lazy as _
from ratrace.common.models import FunctionGroup


class FunctionGroupListView(ListView):
    model = FunctionGroup
    fields = "__all__"
    template_name = "common/functiongroup_list.html"
    queryset = FunctionGroup.objects.all()
    context_object_name = "functiongroups"


class FunctionGroupDetailView(DetailView):
    model = FunctionGroup


class FunctionGroupAddView(CreateView):
    template_name = "common/functiongroup_form.html"
    model = FunctionGroup
    fields = "__all__"
    success_url = "/functiongroups"
    extra_context = {"title": _("Add functiongroup")}


class FunctionGroupUpdateView(UpdateView):
    model: FunctionGroup
    fields = "__all__"
    template_name = "common/functiongroup_form.html"
    queryset = FunctionGroup.objects.all()
    success_url = "/functiongroups"
    extra_context = {"title": _("Edit functiongroup")}


class FunctionGroupDeleteView(DeleteView):
    model = FunctionGroup
    template_name = "common/confirm_delete.html"
    success_url = "/functiongroups"

ratrace/common/views/position.py
from django import forms
# from django.forms import forms
from django.http import request
from django.shortcuts import render
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    DeleteView,
    UpdateView,
)
from django.utils.translation import gettext_lazy as _

from ratrace.common.models import Position, Employee


class PositionListView(ListView):
    model = Position
    fields = "__all__"
    template_name = "common/position_list.html"
    queryset = Position.objects.all()
    context_object_name = "Positions"


class PositionDetailView(DetailView):
    model = Position


# FIXME: Save and successurl not working on save or update


class PositionAddView(CreateView):
    template_name = "common/position_form.html"
    model = Position
    fields = "__all__"
    success_url = "/positions"
    extra_context = {"title": _("Add Position")}

# TODO: forms.MultipleChoiceField(widget=ChEckbox)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["employee_list"] = Employee.objects.all()
        return context


class PositionUpdateView(UpdateView):
    model: Position
    fields = "__all__"
    template_name = "common/position_form.html"
    queryset = Position.objects.all()
    success_url = "/positions"
    extra_context = {"title": _("Edit Position")}


class PositionDeleteView(DeleteView):
    model = Position
    template_name = "common/confirm_delete.html"
    success_url = "/positions"

ratrace/common/templates/layouts/includes/navigation.html
{% load static i18n %}


<header class="header" id="header">
  <div class="header_toggle"><i class='bx bx-menu' id="header-toggle"></i></div>
</header>
<div class="l-navbar" id="nav-bar">
  <nav class="nav">
    <div>
      <a href="{% url 'common:index' %}" class="nav_logo">
        {# FIXME: use a 24px native icon instead of downsampling it. #}
        <img src="{% static 'img/logo150px.png' %}" style="width:28px" alt="">
        <span class="nav_logo-name">RatRace</span>
      </a>
      <div class="nav_list">
        <a href="#" class="nav_link active">
          <i class='bi bi-grid nav_icon'></i>
          <span class="nav_name">{% translate 'Dashboard' %}</span>
        </a>
        <a href="{% url 'common:company-list' %}" class="nav_link">
          <i class='bi bi-building nav_icon'></i>
          <span class="nav_name">{% translate 'Companies' %}</span>
        </a>
{% comment %}        <a href="{% url 'common:departments-list' %}" class="nav_link">
          <i class='bi bi-diagram-3 nav_icon'></i>
          <span class="nav_name">{% translate 'Departments' %}</span>
        </a>{% endcomment %}
        <a href="#" class="nav_link">
          <i class='bi bi-people nav_icon'></i>
          <span class="nav_name">{% translate 'Employees' %}</span>
        </a>
        <a href="{% url 'common:settings' %}" class="nav_link">
          <i class='bi bi-gear nav_icon'></i>
          <span class="nav_name">{% translate 'Settings' %}</span>
        </a>
      </div>
    </div>
    {#        {% if logged_out %}#}
    <a href="#" class="nav_link"><i class='bi bi-door-open'></i><span class="nav_name">Login</span></a>
    {#        {% else %}#}
    {#        <a href="#" class="nav_link"> <i class='bi bi-box-arrow-left nav_icon'></i> <span class="nav_name">Logout</span> </a>#}
    {#        {% endif %}#}
  </nav>
</div>

{#<nav class="navbar navbar-expand-lg navbar-light">#}
{#  <div class="container-fluid">#}
{#    <a class="navbar-brand" href="{% url 'common:index' %}">#}
{#      <img src="{% static 'img/logo150px.png' %}" alt="Logo" width="60px">#}
{#    </a>#}
{#    <ul class="nav nav-tabs">#}
{#      <li class="nav-item menu-text">#}
{#        {% if current_company %}#}
{#          <div class="dropdown">#}
{#            <button class="btn btn-send dropdown-toggle" type="button"#}
{#                    id="dropdownCompanySelect" data-bs-toggle="dropdown"#}
{#                    aria-expanded="false">#}
{#              {{ current_company }}#}
{#            </button>#}
{#            <ul class="dropdown-menu" aria-labelledby="dropdownCompanySelect">#}
{#              {% for company in companies %}#}
{#                <li>#}
{#                   FIXME: changing companies here still does not work. #}
{#                  <button#}
{#                      class="dropdown-item"#}
{#                      hx-post="{% url 'common:company-select' company.id %}"#}
{#                      hx-target="body"#}
{#                  >#}
{#                    {{ company }}#}
{#                  </button>#}
{#                </li>#}
{#              {% endfor %}#}
{#            </ul>#}
{#          </div>#}
{#        {% else %}#}
{#          <a class="nav-link"#}
{#             aria-current="page"#}
{#             href="{% url 'common:company-list' %}"#}
{#             hx-push-url="true"#}
{#          >{% translate 'Select Company' %}</a>#}
{#        {% endif %}#}
{#      </li>#}
{##}
{#    </ul>#}
{#    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"#}
{#            data-bs-target="#navbar-common" aria-controls="navbar-common"#}
{#            aria-expanded="false" aria-label="Toggle navigation">#}
{#      <span class="navbar-toggler-icon"></span>#}
{#    </button>#}
{#    <div class="collapse navbar-collapse" id="navbar-common">#}
{#      <ul class="nav nav-tabs">#}
{#        <li class="nav-item menu-text">#}
{#          <a class="nav-link {% if '/departments' in request.path %}active{% endif %}"#}
{#             aria-current="page" href="{% url 'common:departments-list' %}">{% trans ' Departments' %}</a>#}
{#        </li>#}
{#        <li class="nav-item menu-text">#}
{#          <a class="nav-link {% if '/employeetypes' in request.path %}active{% endif %}"#}
{#             aria-current="page" href="#">{% trans ' Employee-Types' %}</a>#}
{#        </li>#}
{#        <li class="nav-item menu-text">#}
{#          <a class="nav-link {% if '/employees' in request.path %}active{% endif %}"#}
{#             aria-current="page" href="#">{% trans ' Employees' %}</a>#}
{#        </li>#}
{#        <li class="nav-item menu-text">#}
{#          <a class="nav-link {% if '/workingtimes' in request.path %}active{% endif %}"#}
{#             aria-current="page" href="#">{% trans ' Shifts' %}</a>#}
{#        </li>#}
{#        <li class="nav-item menu-text">#}
{#          <a class="nav-link{% if 'login' in request.path %} active{% endif %}"#}
{#             aria-current="page" href="{% url 'common:login' %}"><i#}
{#              class="bi bi-door-open"></i> Login</a>#}
{#        </li>#}
{#      </ul>#}
{#    </div>#}
{#  </div>#}
{#</nav>#}